packages/gatsby-transformer-cloudinary/get-image-objects.js, packages/gatsby-transformer-cloudinary/upload.js
Using the breakpoints generated by Cloudinary means we can’t access query arguments, so instead we can just get a huge set of breakpoints and filter to just the ones we need.
fix #5
=> fix: handle max width up to 5000px

packages/gatsby-transformer-cloudinary/README.md
I was getting a path error.  Using `path: `${__dirname}/src/images`,` resolved it for me
=> add ${__dirname} to path config

packages/gatsby-transformer-cloudinary/upload.js
Fixed the bug with uploading multiple images. The issue was in the responsive breakpoint limit set when uploading to Cloudinary and receiving derived Images.
Also, set defaults for required upload config, with the option for a user to specify in `gatsby-config`. 
todo: update Readme with config options. 
Should close #18 #17 #15 #11
=> [IMPORTANT]: fix bug in uploading large/multiple images

packages/gatsby-transformer-cloudinary/README.md
Updated the readme to include 
1. Details on setting responsive breakpoints on upload.
2. Add an option to create `derivedImages` on upload. 
3. Info on setting the maximum number of breakpoint images to be returned on upload.
=> update readme with responsive breakpoints info

packages/gatsby-transformer-cloudinary/CHANGELOG.md, packages/gatsby-transformer-cloudinary/README.md, packages/gatsby-transformer-cloudinary/gatsby-node.js, packages/gatsby-transformer-cloudinary/package.json
The properties `presentationHeight` and `presentationWidth` were incorrectly added to `CloudinaryAssetFixed` instead of `CloudinaryAssetFluid` in #32.
This PR fixes that and adds documentation for how to use the `CloudinaryAssetFluidLimitPresentationSize` fragment.
=> Fix cloudinary asset fluid limit presentation size

packages/gatsby-transformer-cloudinary/CHANGELOG.md, packages/gatsby-transformer-cloudinary/get-image-objects.js, packages/gatsby-transformer-cloudinary/get-image-objects.test.js
`gatsby-transformer-cloudinary` performs a network request to Cloudinary to get the base64 version of each image when Gatsby queries for an image. In the event that images are duplicated, we can reduce the number of network requests by caching the responses returned from Cloudinary.
In an application with many duplicated images, this dropped the `run page queries` portion of `gatsby develop` from around 700 seconds to under 10 seconds.
=> Cache base64 responses

packages/gatsby-transformer-cloudinary/upload.js, packages/gatsby-transformer-cloudinary/upload.test.js
If multiple images in the file system have the same file name, they are uploaded with the same public ID. This causes Gatsby to put them in GraphQL as childrenCloudinaryAsset instead of childCloudinaryAsset.
When uploading images from the file system, use their path (minus their extension) as their public ID.
=> Fix children cloudinary asset

packages/gatsby-transformer-cloudinary/CHANGELOG.md, packages/gatsby-transformer-cloudinary/README.md, packages/gatsby-transformer-cloudinary/gatsby-node.js, packages/gatsby-transformer-cloudinary/get-image-objects.js, packages/gatsby-transformer-cloudinary/get-image-objects.test.js, packages/gatsby-transformer-cloudinary/package.json
This PR adds the ability to set the height of `fixed` images. For example, if you query with `height: 100`, then the smallest image in the srcSet will have a height of 100. The rest of the srcSet images will have heights that are multiples of the provided height.
=> Height argument for fixed queries

packages/gatsby-transformer-cloudinary/CHANGELOG.md, packages/gatsby-transformer-cloudinary/README.md, packages/gatsby-transformer-cloudinary/package.json, packages/gatsby-transformer-cloudinary/upload.js, packages/gatsby-transformer-cloudinary/upload.test.js
This PR updates `createRemoteImageNode` to use the plugin option `overwriteExisting` when it is not given an `overwrite` argument.
=> Use overwriteExisiting from options if not provided

packages/gatsby-transformer-cloudinary/CHANGELOG.md, packages/gatsby-transformer-cloudinary/gatsby-node.js, packages/gatsby-transformer-cloudinary/get-image-objects.js, packages/gatsby-transformer-cloudinary/get-image-objects/get-shared-image-data.js
When using `gatsby-transformer-cloudinary`, the `run page queries` step often takes a long time without any output. This is problematic because the user doesn't know what is taking so long.
This PR logs each time an API call to Cloudinary is made. It also points users to the README and how they can speed up their build times if they're too slow.
=> Log cloudinary api calls

packages/gatsby-transformer-cloudinary/CHANGELOG.md, packages/gatsby-transformer-cloudinary/gatsby-node.js
This PR fixes an issue that prevented fluid images from using precomputed base64 images.
Before this fix, fluid queries always downloaded base64 images from Cloudinary.
The problem was that base64 images were not being passed from the fluid image resolver to `getFluidImageObject`.
=> Fix fluid defaultBase64 images

packages/gatsby-transformer-cloudinary/CHANGELOG.md, packages/gatsby-transformer-cloudinary/README.md, packages/gatsby-transformer-cloudinary/create-image-node.js, packages/gatsby-transformer-cloudinary/create-image-node.test.js, packages/gatsby-transformer-cloudinary/fragments.js, packages/gatsby-transformer-cloudinary/gatsby-node.js, packages/gatsby-transformer-cloudinary/gatsby-node/create-asset-nodes-from-data.js, packages/gatsby-transformer-cloudinary/gatsby-node/create-asset-nodes-from-data.test.js, packages/gatsby-transformer-cloudinary/get-image-objects.js, packages/gatsby-transformer-cloudinary/get-image-objects.test.js, yarn.lock
This PR adds the ability to pass tracedSVG values from the user's CMS/backend through this plugin into Gatsby GraphQL queries. It also adds a few fragments to make querying for different types of placeholder images easier.
=> Add default traced svg properties

packages/gatsby-transformer-cloudinary/CHANGELOG.md, packages/gatsby-transformer-cloudinary/get-image-objects/get-shared-image-data.js, yarn.lock
This PR improves base64 image caching.
Previously, the base64 cache was updated after the base64 image was received from Cloudinary. If a second request for the image was made before the response came back, then a second API call to Cloudinary would be made.
Now, the promise for the API call is cached instead of the resolved image. This means the cache is updated immediately, and all requests for the same image will resolve from the same promise.
=> Improve base64 caching

packages/gatsby-transformer-cloudinary/CHANGELOG.md, packages/gatsby-transformer-cloudinary/README.md, packages/gatsby-transformer-cloudinary/gatsby-node.js, packages/gatsby-transformer-cloudinary/get-image-objects.js, packages/gatsby-transformer-cloudinary/get-image-objects.test.js
This PR makes it so that Cloudinary API calls for base64 images are only run if the user requests a base64 image with their GraphQL query. For users who do not use base64 images, this will result in much fast builds.
=> Lazy base64 evaluation

.github/workflows/node.js.yml
Remove test on Node 10.x as Gatsby requires at least  12.x
=> Remove support for 10.x

packages/gatsby-transformer-cloudinary/gatsby-image/index.js, packages/gatsby-transformer-cloudinary/gatsby-image/types.js, packages/gatsby-transformer-cloudinary/gatsby-node.js, packages/gatsby-transformer-cloudinary/node-creation/index.js, packages/gatsby-transformer-cloudinary/node-creation/types.js
- Move create CloudinaryAsset type from gatsby-image to node-creation  module
=> refactor: create types

plugin/node-creation/upload.js, plugin/node-creation/upload.test.js, plugin/options.js
Part of #188 since there was breakpoint optimization done on upload for gatsby-image that is no longer in use.
=> refactor: remove upload code only needed by gatsby-image

README.md, plugin/gatsby-plugin-image/generate-asset-url.js, plugin/gatsby-plugin-image/generate-asset-url.test.js, plugin/gatsby-plugin-image/resolve-asset.test.js, plugin/gatsby-plugin-image/resolvers.js
=> fix: gatsbyImageData generates http urls, not https

demo/gatsby-config.js, demo/gatsby-node.js, demo/src/pages/somebaddata.js, plugin/gatsby-plugin-image/index.js, plugin/gatsby-plugin-image/resolve-asset.js, plugin/gatsby-plugin-image/resolve-asset.test.js
When sourcing data every sourced item might _not_ be be valid. Instead of stopping the build an error will be logged. 
Make sure to check if `gatsbyImageData` is not null before using in the `GatsbyImage` component.
Closes #214
=> feat: allow invalid source data by making gatsbyImageData nullable

CHANGELOG.md, demo/gatsby-config.js
* remove demo site author
* remove unnecessary changelog bugfix message
* remove left over merge conflict string
=> chore: pre-release on @latest cleanup

demo/gatsby-config.js, demo/gatsby-node.js, demo/src/pages/manual-tests/no-data.js, demo/src/pages/manual-tests/varied-data.js, demo/src/pages/somebaddata.js, plugin/gatsby-plugin-image/asset-data.js, plugin/gatsby-plugin-image/asset-data.test.js, plugin/gatsby-plugin-image/generate-asset-url.js, plugin/gatsby-plugin-image/resolve-asset.js, plugin/gatsby-plugin-image/resolve-asset.test.js, plugin/package.json, yarn.lock
Uses `probe-image-size` to fetch metadata when its missing, instead of the Cloudinary `getinfo` flag.
Removes the errors reported in #223, but will still not adhere to the `cloudinaryAssetData` flag.
=> fix: problem getting metadata

.releaserc, CHANGELOG.md, README.md, demo/src/pages/manual-tests/cname-private-cdn.js, plugin/gatsby-plugin-image/generate-asset-url.js, plugin/gatsby-plugin-image/generate-asset-url.test.js, plugin/gatsby-plugin-image/resolve-asset.test.js, plugin/gatsby-plugin-image/resolvers.js, plugin/package.json
=> feat: cname, private cdn support
